gazebo_ros_control:
  pid_gains:
    panda_joint1: { p: 12000, d: 0, i: 0.0, i_clamp: 10000 }
    panda_joint2: { p: 30000, d: 0, i: 0.0, i_clamp: 10000 }
    panda_joint3: { p: 30000, d: 0, i: 0.0, i_clamp: 10000 }
    panda_joint4: { p: 18000, d: 0, i: 0.0, i_clamp: 10000 }
    panda_joint5: { p: 12000, d: 0, i: 0.0, i_clamp: 10000 }
    panda_joint6: { p: 7000, d: 0, i: 0.0, i_clamp: 10000 }
    panda_joint7: { p: 2000, d: 0, i: 0.0, i_clamp: 10000 }

    panda_finger_joint1: {p: 100, i: 0, d: 50}
    panda_finger_joint2: {p: 100, i: 0, d: 50}